services:
  app:
    image: kimsudang/nest-js-app:latest
    container_name: app_container
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=myapp_db
      - MYSQL_USER=myapp_user
      - MYSQL_PASSWORD=strongpassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=strongpassword
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - ko-chock-chock

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: myapp_db
      MYSQL_USER: myapp_user
      MYSQL_PASSWORD: strongpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      LC_ALL: C.UTF-8
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p rootpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ko-chock-chock

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
    command: redis-server --requirepass strongpassword --port 6379 --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '-a', 'strongpassword', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ko-chock-chock

  mongodb:
    image: mongo:5.0.9
    container_name: mongo_container
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD-SHELL', "echo 'db.runCommand({ping: 1})' | mongo --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ko-chock-chock

volumes:
  mysql_data:
  redis_data:
  mongo_data:

networks:
  ko-chock-chock:
    driver: bridge
